# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 11 Pro Max",
  "iPhone 11 Pro",
  "iPhone 8 Plus",
  "iPhone SE (2nd generation)",
  # "iPhone SE (1st generation)",

  "iPad Pro (12.9-inch) (4th generation)",
  "iPad Pro (12.9-inch) (2nd generation)",
  # "iPad Air (4th generation)",
  # "iPad (8th generation)",
  # "iPad mini (5th generation)" # crashes
])

# languages([
#   "en-US",
#   "de-DE",
#   "it-IT",
#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
# ])

# The name of the scheme which contains the UI Tests
scheme("Fastlane_Snapshots")

# Where should the resulting screenshots be stored?
# output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

override_status_bar(true)

dark_mode(false)

# For more information about all available options run
# fastlane action snapshot
